packages:
  # demo apps will live in the apps directory
  - 'apps/**'
  # stencil packages will live in the packages directory
  - 'packages/**'
  - 'packages/angular-workspace/projects/**'
  # exclude packages that are inside test directories
  - '!**/test/**'